settings:
  title: 'Status Page'
  url: 'https://status-page.shero.team' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: benchmade
    name: Benchmade Knife Company
    url: 'https://www.benchmade.com/'
    method: GET
    expectStatus: 200
  - id: cheapjoes
    name: Cheap Joes Art Stuff
    url: 'https://www.cheapjoes.com/'
    method: GET
    expectStatus: 200
  - id: tormach
    name: Tormach CNC Machines Tooling and Accessories
    url: 'https://tormach.com/'
    method: GET
    expectStatus: 200
